workflows:
  ios-release:
    name: iOS Release → .ipa
    environment:
      groups:
        - apple_credentials   # ← now pulls your credentials
      vars:
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
      flutter: stable
    triggering:
      events:
        - push
        - tag
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
      - name: Install Pods
        script: |
          cd ios
          pod install
      - name: Build .ipa
        script: |
          flutter build ios --release --no-codesign
          xcodebuild -workspace "$XCODE_WORKSPACE" \
                     -scheme "$XCODE_SCHEME" \
                     -configuration Release \
                     -allowProvisioningUpdates \
                     -archivePath $CM_BUILD_DIR/Runner.xcarchive \
                     archive
          xcodebuild -exportArchive \
                     -archivePath $CM_BUILD_DIR/Runner.xcarchive \
                     -exportOptionsPlist $FCI_BUILD_DIR/exportOptions.plist \
                     -exportPath $CM_BUILD_DIR/IPA
    artifacts:
      - $CM_BUILD_DIR/IPA/*.ipa
    publishing:
      email:
        recipients:
          - castillovinceb@hotmail.com
        notify:
          success: true
          failure: true